package controllers

import (
	"encoding/json"
	"log"
	"net/http"
)

type PushHandler struct{}

type AutoGenerated struct {
	ID   string `json:"id"`
	Name string `json:"name"`
	URI  string `json:"uri"`
	Text string `json:"text"`
}

func (*PushHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	log.Print(5566)
	decoder := json.NewDecoder(r.Body)
	var t AutoGenerated
	err := decoder.Decode(&t)
	if err != nil {
		log.Print(err)
	}
	log.Print(t.ID)
	log.Print(t.Name)
	log.Print(t.URI)
	log.Print(t.Text)

	// linebot.PushMessageCall

	return

}
